### ISSUE TITLE
removeTorrent is not normalized

### ISSUE THREAD

**Issue by craigharman** [scttcper/qbittorrent#95]
According to the docs the remove torrent function should be normalized between:

qbittorrent
deluge
transmission
utorrent
rtorrent

However, removeTorrent here returns a boolean
On Transmission it returns AddTorrentResponse
Deluge returns BooleanStatus
and uTorrent returns BaseResponse

Shouldn't this return a normalised result?

**Comment by scttcper** [comment]
its normalized in that they all have a removeTorrent that accepts the same arguments, but there's only a few functions with normalized results. Its been a little bit since i worked on all of them, but i'm pretty sure they should all throw if the remove fails.  Also I never got around to doing rtorrent.

The interface of the shared functions is here
https://github.com/scttcper/shared-torrent/blob/d6a098aeb51c06448f21706811c25dd4e81d561d/src/index.ts#L3-L17
